#!/usr/bin/env python3
"""Generate the finite float32 sine phases used by the original object methods."""
import math,struct
from pathlib import Path
out=['/* Generated by tools/make_motion_tables.py: original finite sine phases. */','#ifndef DJ_MOTION_TABLES_H','#define DJ_MOTION_TABLES_H']
for name,n,step,amp in [('monster_x',157,.24,10),('monster_y',126,.05,5),('monster_fly_y',42,.15,10),('ufo_x',315,.02,20),('ufo_y',158,.04,10)]:
 vals=[struct.unpack('<f',struct.pack('<f',math.sin(i*step)*amp))[0].hex()+'f' for i in range(n)]
 out.append('static const float '+name+'['+str(n)+'] = {')
 out+=['    '+', '.join(vals[i:i+4])+',' for i in range(0,n,4)]
 out.append('};')
out.append('#endif')
(Path(__file__).resolve().parents[1]/'port/src/motion_tables.h').write_text('\n'.join(out)+'\n')
